DROP TABLE IF EXISTS TB_HEROIS;

CREATE TABLE TB_HEROIS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    POWER TEXT NOT NULL
)

-- CREATE
INSERT INTO TB_HEROIS (NAME, POWER)
VALUES
    ('Flash', 'Speed'),
    ('Aquaman', 'Watter Control'),
    ('Batman', 'Money')

-- READ
SELECT * FROM TB_HEROIS;
SELECT * FROM TB_HEROIS WHERE NAME = 'Flash';

-- UPDATE
UPDATE TB_HEROIS
SET NAME = 'Goku', POWER = 'God'
WHERE ID = 1;

-- DELETE 
DELETE FROM TB_HEROIS WHERE ID = 2;